apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgmyadmin-deployment
  labels:
    app: pgmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgmyadmin
  template:
    metadata:
      labels:
        app: pgmyadmin
    spec:
      volumes:
        - name: pv-config
          persistentVolumeClaim:
            claimName: pvc-pgmyadmin
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        volumeMounts:
          - name: pv-config
            mountPath: "/var/lib/pgadmin"
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: user@somedomain.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: choose_the_initial_pgadmin_password
        livenessProbe:
          httpGet:
              path: /
              port: 80
          periodSeconds: 10
          failureThreshold: 20
---
apiVersion: v1
kind: Service
metadata:
  name: pgmyadmin-service
spec:
  type: LoadBalancer
  selector:
    app: pgmyadmin
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
